import { env } from '@/env.mjs';

export const DATABASE_ID = env.NEXT_PUBLIC_APPWRITE_DATABASE_ID;
export const WORKSPACES_ID = env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID;
export const IMAGES_BUCKET_ID = env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID;
export const MEMBERS_ID = env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID;
export const PROJECT_ID = env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID;
